### PR TITLE
Updates to the editor navigation bar

### PR DESCRIPTION
**Pull request by skearnes**
Related to #404 

* Changes sidebar behavior to scroll to the selected section rather than show/hide.
* Adds support for updating the sidebar selection as the user scrolls.

NOTE: The dynamic sidebar selection is quite complicated---how do you decide which section you're "in"? As a way of sidestepping this issue I chose to highlight the names of any sections that are currently visible:

image

### CODE REVIEW

**Comment by skearnes** [comment]
Update: I played with this some more and have a mostly functional single-selection sidebar working. It jumps around a bit when scrolling by the smaller sections but generally behaves as you'd expect.

**Comment by connorcoley** [comment]
I like the scrolling to the position but I do find the behavior of the sidebar a little unintuitive now. It seems to select whichever section has most recently come into frame. If you try to navigate to Notes after being further down, for example, you end up with "Notes" selected. If you navigate to Notes after being further up, you can end up with Outcomes selected depending on the size of your window and display resolution. Notes will be at the top of the page though, which is good

**Comment by skearnes** [comment]
Yeah it's going to be tricky to get that right, I think. What do you think of the multi-selection option from the original description?

**Comment by connorcoley** [comment]
I don't think the multi-selection is a bad idea necessary...it would highlight anything that's visible on the page. It will be pretty useful when we have individual inputs listed under Inputs

**Comment by skearnes** [comment]
OK, I reverted to the original multi-selection proposal. We can fix single-selection later if we want. PTAL.

**Review by connorcoley — APPROVED** [review]

**Pull request merged**
