### PR TITLE
Add BinaryData message

### PR DESCRIPTION
**Pull request by skearnes**
I wanted to include more metadata for `bytes` values, so I created a `BinaryData` message and replaced maps with repeated fields. 

Happy to keep using maps if we also want "names" for these messages...

### CODE REVIEW

**Comment by connorcoley** [comment]
A nice aspect of the map is that we are consistent with the convention that map string keys just need to be internally consistent and don't carry outside meaning (i.e., like the names of analyses and the names of reaction inputs).

Pros:
- Having a ```description``` field

Cons:
- Another level of nested messages
- Implies a greater significance of the ```filename``` field when we really just care about the file type / extension. 

Neurals?
- Fewer map fields in the schema

How would you feel about using a ```map<string, BinaryData>``` where the ```BinaryData``` message only contains ```bytes``` and ```description``` fields? We could have an optional ```filetype``` field that could be used if the map key doesn't use a known extension.

**Comment by skearnes** [comment]
> How would you feel about using a `map<string, BinaryData>` where the `BinaryData` message only contains `bytes` and `description` fields? We could have an optional `filetype` field that could be used if the map key doesn't use a known extension.

Great idea. PTAL.

**Comment by connorcoley** [comment]
I approved this PR, but would you be able to add a validator for this new message type? Every time we create a new message in the schema we need to add it to the validations. Perhaps all we need to do is check that ```value``` is defined

**Comment by skearnes** [comment]
> I approved this PR, but would you be able to add a validator for this new message type? Every time we create a new message in the schema we need to add it to the validations. Perhaps all we need to do is check that `value` is defined

Thanks for the reminder! Done.

**Pull request merged**
