### PR TITLE
Make formatters a check rather than a fix

### LINKED ISSUE #288: linting a pre-merge check, not a code bot
If the lint checks were a merge condition rather than a file-modifying daemon, then I could run yapf when I feel like it instead of facing a more time consuming and repetitive merge chore when I push, and there would be no effect on conformance in the repo.

### PR DESCRIPTION
**Pull request by skearnes**
Fixes #288 

* Moves linters and formatters to `cleanup.yml` (now `run_tests.yml` only runs actual tests)
* Runs linters and formatters in "check" mode; actions will fail if files are not formatted properly
* Adds `format.sh` script for formatting files locally (which can then be committed)

I'm happy to block on #285 to make merging easier for @n8kim1 if you'd like.

### CODE REVIEW

**Comment by connorcoley** [comment]
`format.sh` isn't very cross-platform friendly (e.g., uses `find`), and doesn't provide any checks that things are installed (e.g., Go). I'm having trouble getting `addlicense` to run locally. Having to set everything up to run `format.sh` locally will slightly raise the barrier to contributing. 

Would a compromise to @antonkast-google 's comments be to have the _option_ to run this script locally but still include it as an action?

**Comment by skearnes** [comment]
> `format.sh` isn't very cross-platform friendly (e.g., uses `find`), and doesn't provide any checks that things are installed (e.g., Go). I'm having trouble getting `addlicense` to run locally. Having to set everything up to run `format.sh` locally will slightly raise the barrier to contributing.
> 

This works on mac and linux, but I agree that not checking for things being installed is annoying. I did include the installation commands in comments, but they only work on linux.

> Would a compromise to @antonkast-google 's comments be to have the _option_ to run this script locally but still include it as an action?

In general I agree with Anton that auto-commits are a bit disruptive and non-standard (we started doing this as part of the submission pipeline to keep the directory layout sane), but I don't feel strongly about this and think your compromise is reasonable.

**Comment by skearnes** [comment]
Whatever we decide, I'm pretty happy with the refactoring I did here and it's small changes to go back to auto-commits.

**Comment by skearnes** [comment]
PTAL and try `format.sh` again...it's a bit friendlier now

**Comment by connorcoley** [comment]
> PTAL and try `format.sh` again...it's a bit friendlier now

Thanks for these changes

**Comment by n8kim1** [comment]
Having some trouble running format.sh -- adding licenses isn't working... The script is trying to add licenses to all the files I have (including the gitignore'd third-party code), and so it's spitting out "too many open files" for each of these files.

Is there a workaround? I don't want to temporarily delete the third-party files, but can't think of much better.

**Comment by skearnes** [comment]
Can you just comment out that line in format.sh temporarily? I'll look into it.

**Comment by n8kim1** [comment]
Yep, thanks!

**Pull request merged**
