### PR TITLE
Add install_requires to setup.py

### LINKED ISSUE #600: Setup.py is missing install_requires
setup.py is missing `install_requires`, so dependencies are not installed when installing from pypi.  Happy to submit a PR for this if it is indeed a bug.

### PR DESCRIPTION
**Pull request by marcosfelt**
This fixes #600 by making sure dependencies are installed when the package is installed from pypi or source via pip. This avoids having to clone the whole repository in order to get the package installed.

### CODE REVIEW

**Comment by marcosfelt** [comment]
Any updates on this @skearnes

**Review by skearnes — APPROVED** [review]

**Comment by skearnes** [comment]
Thanks @marcosfelt; sorry for the delay!

**Comment by skearnes** [comment]
@marcosfelt I think you need to run the format.sh script before this can be merged, so the check_python test will pass.

**Comment by dcambie** [comment]
> @marcosfelt I think you need to run the format.sh script before this can be merged, so the check_python test will pass.

In this case this should be enough ;)
```console
pip install yapf
yapf -i .\setup.py
```

**Pull request closed without merging**
