### PR TITLE
Using warnings module for ValidationWarnings

### PR DESCRIPTION
**Pull request by connorcoley**
- ```raise``` interrupts the program like an Exception
- ```validate_binary_data``` was missing ```return message```

### CODE REVIEW

**Comment by skearnes** [comment]
I was thinking that we wanted validation errors to be fatal? I'm not aware of a way to catch warnings; I'd suggest putting a try/except block in `validate_message` and adding a boolean argument `errors_are_fatal`.

**Comment by connorcoley** [comment]
I agree that errors should be fatal, but I think that we should also have non-fatal warnings. For example, with a ```Percentage``` message with ```value=0.5``. You _could_ have 0.5% yield legitimately, but there is a high chance that they means 0.5 = 50% yield. 

There are ways to change the behavior of warnings (see [here](https://docs.python.org/3/library/warnings.html#the-warnings-filter)).

**Comment by skearnes** [comment]
Oh I see. Sorry, it wasn't clear that these were warnings flagging potential issues that might be legitimate.

**Comment by connorcoley** [comment]
That's my bad for not putting an informative comment on this PR, sorry

**Pull request merged**
