### PR TITLE
Show inputs in the sidebar

### PR DESCRIPTION
**Pull request by skearnes**
Related to #404 

Note that getting the in-view/selected input to highlight will involve some extra work resetting the `InteractionObserver` etc.

image

### CODE REVIEW

**Comment by skearnes** [comment]
I can probably just create a separate `InteractionObserver` for each input; that should make things much easier...I'll still do this in a different PR.

**Comment by connorcoley** [comment]
Few things:
- On load (e.g., of the full reaction pbtxt example), the sidebar contains a single "Input 0" rather than what the loaded reaction contains (e.g., the two inputs with names "4" and "")
- Removing an input does not trigger the sidebar to be updated
- Should we only call `updateSidebar` when an input is added/removed or has its name changed? Rather than with any change within the whole input node? 

I do think resetting the InteractionObserver will be a nice feature. Note that the section highlighting doesn't take into account the portion of the form occluded by the header, so when I click on "Inputs", "Identifiers" is still also selected. You might consider including that in the same issue for adding input-level highlighting

**Comment by skearnes** [comment]
> Few things:
> 
> * On load (e.g., of the full reaction pbtxt example), the sidebar contains a single "Input 0" rather than what the loaded reaction contains (e.g., the two inputs with names "4" and "")

Good catch; this wasn't happening on the Nielsen test data. The problem seems to be that `updateSidebar` was called only once sometime during the form initialization. Seems to be fixed now.

> * Removing an input does not trigger the sidebar to be updated

Fixed.

> * Should we only call `updateSidebar` when an input is added/removed or has its name changed? Rather than with any change within the whole input node?

Good idea. Done.
 
> I do think resetting the InteractionObserver will be a nice feature. Note that the section highlighting doesn't take into account the portion of the form occluded by the header, so when I click on "Inputs", "Identifiers" is still also selected. You might consider including that in the same issue for adding input-level highlighting

Will do.

**Comment by connorcoley** [comment]
More comments:
- There is now an error being printed to the console when loading a reaction (e.g., the full example). This might be unrelated to the current PR, but it's happening in the sidebar when calling `clearSelected()` on undefined.
- I can no longer remove an input: `Uncaught TypeError: Cannot read property 'remove' of undefined`. I think you forgot to add `ord.inputs.remove` to the `exports`? 
- Given that you're calling `ord.inputs.updateSidebar();` from workups.js, I think you should keep it in `ord.reaction` since that is the catch-all for any form-wide js functions. As a related question, why do you need to update the sidebar after adding a workup input node?

**Comment by skearnes** [comment]
> More comments:
> 
> * There is now an error being printed to the console when loading a reaction (e.g., the full example). This might be unrelated to the current PR, but it's happening in the sidebar when calling `clearSelected()` on undefined.

I noticed that too. Some quick attempts to fix it failed miserably; I think it's unrelated to this PR.

> * I can no longer remove an input: `Uncaught TypeError: Cannot read property 'remove' of undefined`. I think you forgot to add `ord.inputs.remove` to the `exports`?

Fixed.

> * Given that you're calling `ord.inputs.updateSidebar();` from workups.js, I think you should keep it in `ord.reaction` since that is the catch-all for any form-wide js functions. As a related question, why do you need to update the sidebar after adding a workup input node?

This is because `updateSidebar` grabs everything with the `input` class, including a newly added workup input. The extra call in workups.js is to remove workup inputs from the list (since `updateSidebar` excludes nodes with the `workup_input` class). I think I want to keep this function in inputs.js, so I've updated `ord.inputs.add` to allow the `workup_input` class to be added on creation of the new node and avoids having to call `updateSidebar` twice. (Note that there are other calls to `ord.inputs.*` functions in workups.js already.)

**Review by connorcoley — APPROVED** [review]

**Pull request merged**
