### PR TITLE
Show a table of results in the query interface

### PR DESCRIPTION
**Pull request by skearnes**
Note that this PR is based on #362

Uses [DataTables](https://datatables.net/) for showing query results. The table is created on demand, so we don't have to wait for the reaction tables/images to render for all of the results before we show the page---only the current page of results is rendered. It's still pretty slow, but maybe we can speed it up by using smaller images?

### CODE REVIEW

**Comment by skearnes** [comment]
PS it's _way_ faster to generate the HTML table using SVGs instead of PNGs...

**Comment by connorcoley** [comment]
Looks great -- much better than just having the pbtxt. A few nitpicky things (which can be improved in time):

- "Search" is really searching/downselected by reaction ID, right?
- The "Reagents" and "Reactions" selector at the top could be clearer if prepended with "Search by". I also think "Reagents" should be switched to "Components" or "Compound" since reagent holds a more particular meaning in synthesis
- Searching by reaction ID (e.g., ord-008793d82f684c548c06ceba947fa47a) took a _very_ long time and I'm not sure why. Is there no index on this field? It could just be my computer.
- I think if you try to search by "Reagents" but have part of the "Reactions" field populated, it affects the query

**Comment by skearnes** [comment]
> Looks great -- much better than just having the pbtxt. A few nitpicky things (which can be improved in time):
> 
> * "Search" is really searching/downselected by reaction ID, right?

Do you mean the search bar on the table? Yes, that's just searching in the table of returned results.

> * The "Reagents" and "Reactions" selector at the top could be clearer if prepended with "Search by". I also think "Reagents" should be switched to "Components" or "Compound" since reagent holds a more particular meaning in synthesis

Agreed.

> * Searching by reaction ID (e.g., ord-008793d82f684c548c06ceba947fa47a) took a _very_ long time and I'm not sure why. Is there no index on this field? It could just be my computer.

Interesting, this always goes pretty quickly for me locally. We can run more tests as we polish the interface in later PRs.

> * I think if you try to search by "Reagents" but have part of the "Reactions" field populated, it affects the query

Yes, "Reactions" has precedence. We should have the query give precedence to whichever tab was active on "Go".

**Comment by skearnes** [comment]
PTAL; updated with #362 base post-merge.

**Review by connorcoley — APPROVED** [review]

**Pull request merged**
