### PR TITLE
Sort out docker-compose for the web interface

### PR DESCRIPTION
**Pull request by skearnes**
The following commands assume that the `ord-postgres` image is either built locally or pulled from Docker Hub:

```
$ cd .../ord-schema
$ docker build --file=ord_schema/interface/Dockerfile -t openreactiondatabase/ord-interface .
$ cd ord_schema/interface
$ docker-compose up
```

Now the interface is available at `localhost:5000`

### CODE REVIEW

**Comment by connorcoley** [comment]
Debugging in progress...

```
$ docker-compose up
Creating network "interface_default" with the default driver
Creating interface_ord-postgres_1 ... done
Creating interface_web_1          ... done
Attaching to interface_ord-postgres_1, interface_web_1
ord-postgres_1  | 
ord-postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
ord-postgres_1  | 
ord-postgres_1  | 2020-09-15 21:40:27.496 UTC [1] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
ord-postgres_1  | 2020-09-15 21:40:27.497 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
ord-postgres_1  | 2020-09-15 21:40:27.497 UTC [1] LOG:  listening on IPv6 address "::", port 5432
ord-postgres_1  | 2020-09-15 21:40:27.501 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
ord-postgres_1  | 2020-09-15 21:40:27.516 UTC [27] LOG:  database system was interrupted; last known up at 2020-07-15 22:47:08 UTC
web_1           | [2020-09-15 21:40:27 +0000] [6] [INFO] Starting gunicorn 20.0.4
web_1           | [2020-09-15 21:40:27 +0000] [6] [INFO] Listening at: http://0.0.0.0:5000 (6)
web_1           | [2020-09-15 21:40:27 +0000] [6] [INFO] Using worker: sync
web_1           | [2020-09-15 21:40:27 +0000] [9] [INFO] Booting worker with pid: 9
ord-postgres_1  | 2020-09-15 21:40:30.711 UTC [27] LOG:  database system was not properly shut down; automatic recovery in progress
ord-postgres_1  | 2020-09-15 21:40:30.715 UTC [27] LOG:  redo starts at 0/1645C38
ord-postgres_1  | 2020-09-15 21:40:30.808 UTC [27] LOG:  invalid record length at 0/286E4F0: wanted 24, got 0
ord-postgres_1  | 2020-09-15 21:40:30.808 UTC [27] LOG:  redo done at 0/286D7A0
ord-postgres_1  | 2020-09-15 21:40:30.979 UTC [1] LOG:  database system is ready to accept connections
ord-postgres_1  | 2020-09-15 21:40:41.942 UTC [34] FATAL:  password authentication failed for user "ord-postgres"
ord-postgres_1  | 2020-09-15 21:40:41.942 UTC [34] DETAIL:  Role "ord-postgres" does not exist.
ord-postgres_1  | 	Connection matched pg_hba.conf line 95: "host all all all md5"
web_1           | [2020-09-15 21:40:41,943] ERROR in app: Exception on / [GET]
web_1           | Traceback (most recent call last):
web_1           |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
web_1           |     response = self.full_dispatch_request()
web_1           |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
web_1           |     rv = self.handle_user_exception(e)
web_1           |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
web_1           |     reraise(exc_type, exc_value, tb)
web_1           |   File "/opt/conda/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
web_1           |     raise value
web_1           |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
web_1           |     rv = self.dispatch_request()
web_1           |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
web_1           |     return self.view_functions[rule.endpoint](**req.view_args)
web_1           |   File "/usr/src/app/ord-schema/ord_schema/interface/search.py", line 80, in show_root
web_1           |     dataset = connect().run_query(command, return_ids=True)
web_1           |   File "/usr/src/app/ord-schema/ord_schema/interface/search.py", line 100, in connect
web_1           |     port=5432)
web_1           |   File "/opt/conda/lib/python3.7/site-packages/ord_schema-0.0.0-py3.7.egg/ord_schema/interface/query.py", line 392, in __init__
web_1           |     port=port)
web_1           |   File "/opt/conda/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
web_1           |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1           | psycopg2.OperationalError: FATAL:  password authentication failed for user "ord-postgres"
web_1           | 
web_1           | 172.18.0.1 - - [15/Sep/2020:21:40:41 +0000] "GET / HTTP/1.1" 500 290 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
ord-postgres_1  | 2020-09-15 21:40:41.958 UTC [35] FATAL:  password authentication failed for user "ord-postgres"
ord-postgres_1  | 2020-09-15 21:40:41.958 UTC [35] DETAIL:  Role "ord-postgres" does not exist.
ord-postgres_1  | 	Connection matched pg_hba.conf line 95: "host all all all md5"
web_1           | 172.18.0.1 - - [15/Sep/2020:21:40:41 +0000] "GET / HTTP/1.1" 500 290 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36"
web_1           | [2020-09-15 21:40:41,959] ERROR in app: Exception on / [GET]
web_1           | Traceback (most recent call last):
web_1           |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
web_1           |     response = self.full_dispatch_request()
web_1           |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
web_1           |     rv = self.handle_user_exception(e)
web_1           |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
web_1           |     reraise(exc_type, exc_value, tb)
web_1           |   File "/opt/conda/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
web_1           |     raise value
web_1           |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
web_1           |     rv = self.dispatch_request()
web_1           |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
web_1           |     return self.view_functions[rule.endpoint](**req.view_args)
web_1           |   File "/usr/src/app/ord-schema/ord_schema/interface/search.py", line 80, in show_root
web_1           |     dataset = connect().run_query(command, return_ids=True)
web_1           |   File "/usr/src/app/ord-schema/ord_schema/interface/search.py", line 100, in connect
web_1           |     port=5432)
web_1           |   File "/opt/conda/lib/python3.7/site-packages/ord_schema-0.0.0-py3.7.egg/ord_schema/interface/query.py", line 392, in __init__
web_1           |     port=port)
web_1           |   File "/opt/conda/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
web_1           |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
web_1           | psycopg2.OperationalError: FATAL:  password authentication failed for user "ord-postgres"
```

**Comment by connorcoley** [comment]
Issue was an outdated version of the database image defined locally, which did not have the expected username/password defined. Need to fix .yml to ensure the db image is up to date.

Using `docker pull` to get the latest "openreactiondatabase/ord-postgres:latest" worked

**Comment by skearnes** [comment]
Running `docker-compose pull && docker-compose up` should do the trick (note that the `&&` will fail until we get `ord-interface` up on docker hub...)

**Comment by connorcoley** [comment]
Is there a way to build the pull command for the image into the yml file (i.e., make sure the version is up-to-date)?

**Comment by skearnes** [comment]
> Is there a way to build the pull command for the image into the yml file (i.e., make sure the version is up-to-date)?

AFAICT this isn't possible

**Review by connorcoley — APPROVED** [review]
https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375

We could use explicit versioning and not rely on the "latest" tag. Or, just adding the pull command to the code snippet for building/deploying seems okay. The latter might be easiest.

**Comment by skearnes** [comment]
> https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375
> 
> We could use explicit versioning and not rely on the "latest" tag. Or, just adding the pull command to the code snippet for building/deploying seems okay. The latter might be easiest.

I'm not opposed to using different tags. To make this work with automated builds, we'd need to add tags to the repo as well, but that's fine too.

**Pull request merged**
