### PR TITLE
update protobuf version

### PR DESCRIPTION
**Pull request by skearnes**

### CODE REVIEW

**Comment by skearnes** [comment]
Looks like the reason we pin to <3.20 is for compatibility with TensorFlow: https://github.com/tensorflow/tensorflow/blob/b59935d3b349e752eed4729606e5d64a17e48015/tensorflow/tools/pip_package/setup.py#L105

**Comment by skearnes** [comment]
> Looks like the reason we pin to <3.20 is for compatibility with TensorFlow: https://github.com/tensorflow/tensorflow/blob/b59935d3b349e752eed4729606e5d64a17e48015/tensorflow/tools/pip_package/setup.py#L105

FYI @connorcoley @ipendlet @FanwangW we use TF in some of the examples

**Comment by connorcoley** [comment]
Is this a reason to separate out the examples into their own repo? Seems like a complex dependency to have when it's not essential for many use cases

**Comment by skearnes** [comment]
> Is this a reason (or an excuse) to separate out the examples into their own repo? Seems like a complex dependency to have when it's not essential for many use cases

That wouldn't fix the issue; if until TF supports protobuf>=3.20 we won't be able to use TF and ord-schema in the same interpreter since both require the proto libraries. I think our choices are (1) pin to whatever version of protobuf TF supports so that people can use TF, or (2) upgrade protobuf and declare that ord-schema cannot be used with TF.

**Comment by FanwangM** [comment]
I think it's not worth it to lose the support of TF because of version updating. We can just keep the current version and wait for TF to support `protobug>=3.20`.

**Pull request closed without merging**
