### PR TITLE
Do not resolve NAME identifiers during submission

### PR DESCRIPTION
**Pull request by skearnes**
We're hitting the resolution servers millions of times in https://github.com/open-reaction-database/ord-data/pull/59 (if I hadn't stopped the job early).

### CODE REVIEW

**Comment by connorcoley** [comment]
Aside from the flood of requests for this giant PR, are you opposed to using the name resolver upon submission in general?

**Comment by skearnes** [comment]
> Aside from the flood of requests for this giant PR, are you opposed to using the name resolver upon submission in general?

I guess I don't feel strongly about that. It might be better to change the validations so that we warn when there are only NAME identifiers (that might be there already?) rather than actually adding the resolved SMILES during submission? I guess I'm thinking that we shouldn't be doing work that we should be pushing onto the submitters...

**Comment by skearnes** [comment]
PS part of my thinking here, besides the USPTO submission, is around whether contributors can verify changes. We do this resolution in the second phase of the submission where the contributor is not usually involved, and I think I'd prefer that these resolutions be done by the contributors themselves in the first phase instead.

**Comment by connorcoley** [comment]
> PS part of my thinking here, besides the USPTO submission, is around whether contributors can verify changes. We do this resolution in the second phase of the submission where the contributor is not usually involved, and I think I'd prefer that these resolutions be done by the contributors themselves in the first phase instead.

This is convincing for me

**Review by connorcoley — APPROVED** [review]

**Pull request merged**
