### PR TITLE
Adjustments to message names in ProductMeasurement

### PR DESCRIPTION
**Pull request by skearnes**
Adjusts some message/enum naming to avoid unnecessary verbosity.

@connorcoley @michaelmaser It's not clear to me that `MassSpecMeasurementType`/`MassSpecDetails` should be in `ProductMeasurement` instead of `Analysis`?

### CODE REVIEW

**Review by connorcoley — APPROVED** [review]
The MS details do make sense in here, since they don't refer to the method of conducting the analysis itself, but rather how a quantitative performance metric was extracted. It's similar to specifying the wavelength at which a UV peak area was quantified in an LC trace: the full LC analysis will contain multiple wavelengths, but you'll generally use a single one when integrating to find peak areas. 

Edit: I suppose we could add a `Wavelength wavelength` to the measurement as well...

**Comment by skearnes** [comment]
Ah ok; so just to be clear, the values in the MassSpecDetails message may be different for measurements based on the same analysis?

**Comment by connorcoley** [comment]
> Ah ok; so just to be clear, the values in the MassSpecDetails message may be different for measurements based on the same analysis?

Yes, exactly

**Comment by skearnes** [comment]
Added a Wavelength message; PTAL.

**Comment by connorcoley** [comment]
LGTM

**Comment by skearnes** [comment]
FYI Also switched `MassSpecDetails` to `MassSpecMeasurementDetails` but kept the field name as `mass_spec_details`.

**Pull request merged**
